apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmanager
  labels:
    database: postgresql
    type: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: dbmanager
        image: abolfazlyarian/database-manager
        env:
          - name: POSTGRES_DB 
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_HOST
            value: postgresql-headless.default.svc.cluster.local
          - name: namespace
            value: yarian
          - name: DB_PASS
            value: '12345'
      serviceAccountName: dbmanger
