apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-watcher-binding
subjects:
- kind: ServiceAccount
  name: dbmanger
  namespace: yarian
roleRef:
  kind: Role
  name: namespace-watcher
  apiGroup: rbac.authorization.k8s.io
