apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-manager
  labels:
    database: postgresql
    type: manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: POSTGRES_DB 
            value: {{ .Values.env.postgresName }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: postgresUser
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: postgresPassword
          - name: POSTGRES_HOST
            value: {{ .Values.env.postgresHost }}
          - name: namespace
            value: {{ .Values.env.namespace }}
          - name: DB_PASS
            value: "{{ .Values.env.newPass }}"
      serviceAccountName: {{ .Release.Name }}-service
