apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dbmanager
  labels:
    database: postgresql
    type: manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: POSTGRES_DB 
            value: {{ .Values.env.POSTGRES_DB }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: POSTGRES_HOST
            value: {{ .Values.env.POSTGRES_HOST }}
          - name: namespace
            value: {{ .Values.env.Namespace }}
          - name: DB_PASS
            value: "{{ .Values.env.db_pass }}"
      serviceAccountName: {{ .Values.ServiceAccountName }}
