apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-watcher-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.ServiceAccountName }}
  namespace: {{ .Values.env.Namespace }}
roleRef:
  kind: Role
  name: namespace-watcher
  apiGroup: rbac.authorization.k8s.io
