apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespaceWatcherBinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Values.env.namespace }}
roleRef:
  kind: Role
  name: namespaceWatcher
  apiGroup: rbac.authorization.k8s.io
